- .gitmodules
The URL given to the submodule [dcos/dcos](https://github.com/dcos/dcos) is the one used with the SSH key. However this causes issues when simply trying to clone recursively the repository [dcos/dcow-windows](https://github.com/dcos/dcos-windows) with the public HTTPs URLs.
Usage example: http://paste.openstack.org/show/m3yyrOvOcrNisp3Cq3aV
It makes more sense to simply have the public URL for the submodule as well, since that submodule repository is also public.
> Change dcos/dcos submodule to public HTTPs git URL

- scripts/mesos-agent-setup.ps1
This adds an environment file for the mesos agent service that is apparently sourced by the new service wrapper, in the same way that the spartan service sources its own environment file. Compare to lines 131-139 of spartan-agent-setup.ps1.
I've tested this and I've confirmed that these environment variables are set for the mesos-agent.exe process
> Added environment file for mesos agent service.

- scripts/mesos-agent-setup.ps1
This pull request introduces the following updates:
- File used for `--external_log_file` must exist. If the file doesn't exist, the following error is given:
```
Log file created at: 2018/01/16 10:37:02
Running on machine: 15580ACS000000
E0116 10:37:02.354581  1372 slave.cpp:1009] Failed to attach 'C:\DCOS\mesos\log\mesos-service.err.log' to virtual path '/slave/log': Failed to get realpath of 'C:\DCOS\mesos\log\mesos-service.err.log': Failed to get attributes for file 'C:\DCOS\mesos\log\mesos-service.err.log': The system cannot find the file specified.
```
- Set hostname explicitly for the Windows Mesos slave. If not set, the default hostname advertised to master nodes is the same one for all the Windows slaves:
```
$ dcos node
HOSTNAME                                     IP …
```
> Fix external_log_file functionality and explicitly set Mesos Windows slave hostname

- scripts/DCOSWindowsAgentSetup.ps1
- scripts/Modules/Utils/Utils.psm1
- scripts/epmd-agent-setup.ps1
- scripts/mesos-agent-setup.ps1
- scripts/spartan-agent-setup.ps1
- scripts/templates/spartan/sys.spartan.config
- scripts/variables.ps1
This pull request adds the following updates:
- Rename custom NAT network from `nat_network` to `customnat`
- Add logic to update Docker to the latest CE version in order to have https://github.com/docker/libnetwork/commit/884eaa0157709a3197b9696981c4f1ce0d86120b commit in the build. This will allow us to remove all the Spartan workarounds to get it working.
- Remove Spartan workarounds around the broken Docker version
- Add `LogFile` to the `New-DCOSWindowsService` utils function
- Add logging to file to all the wrapped DCOS services
> Update Docker to latest CE and remove Spartan workarounds

- scripts/spartan-agent-setup.ps1
After the Spartan local addresses are set up, it takes a few seconds until they become usable.
This will allow the `spartan-agent-setup.ps1` script to check that the Spartan local addresses are reachable before starting `dcos-spartan` service.
> Test Spartan local addresses connectivity

- scripts/DCOSWindowsAgentSetup.ps1
Fix `Get-MasterIPs` function
If you return an array with a single item from a function in
PowerShell, the language will automatically unpack the array
and return the item instead.
We need `Get-MasterIPs` function to always return a list of IPs.
> Fix `Get-MasterIPs` function

- scripts/DCOSWindowsAgentSetup.ps1
- scripts/dcos-net-agent-setup.ps1
- scripts/templates/dcos-net/sys.config
* Use `config_dir` instead of the env variable `DCOS_NET_CONFIG_DIR`
* Disable Metrics agent if Mesos `authenticate_agents` flag is enabled
> Use config_dir instead of the env variable DCOS_NET_CONFIG_DIR, disable Metrics if mesos_auth is enabled

- scripts/DCOSWindowsAgentSetup.ps1
DC/OS Diagnostics couldn't be properly set up after PR https://github.com/dcos/dcos-windows/pull/36 was merged.
Without this fix, the provisioning VM extension for the Windows VMs will always time out.
The cause for this is the fact that `-DiagnosticsWindowsBinariesURL $DIAGNOSTICS_BINARIES_URL` was removed [here](https://github.com/dcos/dcos-windows/pull/36/commits/fe0f53440921d5ff2158804c131a477607b2d3f6#diff-410134c80a3af7080cc11bcacbe3688dL167).
> Fix regression with diagnostics agent setup

- scripts/Modules/Utils/Utils.psm1
Until now we restarted the service every time it did not gracefully stopped,
with 1 second delay between restarts.
This patch proposes a new default behaviour.
The first two restart come instantly while for the third restart we add a 30
second timeout.
We reset the flags above if and only if the service was running for more than
40 seconds.
I.E.:
In the case a service is broken now it will have the following behaviour
from the point of view of SCM:
```(start *)``` - restart (0 ms) - restart (0 ms) - restart (30 seconds) - restart (30 seconds) - ...
We will go back to ```(start *)``` if the service was up and running for >= ```40 seconds```.
This will aid debugging and cause less spam in logs.
Small nit also add a line ending.
> Change the default service behaviour creation

- scripts/DCOSWindowsAgentSetup.ps1
Prior to this change, this was exactly like [this one](https://github.com/dcos/dcos-windows/blob/bf628274a8d91c7b95ca46eef25f61e176e60d8b/scripts/DCOSWindowsAgentSetup.ps1#L228).
> Fix exception message

- scripts/diagnostics-agent-setup.ps1
* Use service names global variables instead of hard-coded values
* Add adminrouter to the list of monitored services by DC/OS diagnostics
> Add adminrouter to monitored services and remove hard-coded service names values

- scripts/Modules/Utils/Utils.psm1
This patch fixes service creation for services which have log file specified.
The issue before was when expanding the paramaters to the `sc.exe` command.
> fix service creation when log rotation is enabled

- scripts/DCOSWindowsAgentSetup.ps1
This is to make sure the  customnat creation  is before the DCOS-NET to avoid unreliable DNS service on the agent node we have observed on RS4.
> Moved the creation of customnat before dcos-net service

- scripts/templates/dcos-net/sys.config
In the Windows's DCOS-NET implementation, handler_limit was set to 16. This caused DNS on the Windows agent node not to function reliable (some time stop working) on a agent node that has 16+ cpu (such as Standard_D32_V3 Azure Vm size)
Here is how it happened
DCOS-Net leverages a sidejob library for the load-balancing its DNS work load:
In
https://github.com/dcos/dcos-net/blob/1dde472118cc0c52374376bce7729d9107796456/apps/dcos_dns/src/dcos_dns_sup.erl#L41
https://github.com/basho/sidejob/blob/463a4d7b367536a9d29c3c17e63656914107a93a/src/sidejob.erl#L54
https://github.com/basho/sidejob/blob/463a4d7b367536a9d29c3c17e63656914107a93a/src/sidejob.erl#L41
there is a calculation on the number of task could be queued or scheduled to a work thread
WorkerLimit = Limit div Workers,
where: Workers is …
> Removed  the handler_limit from DCOS-net service sys.config file

- scripts/dcos-net-agent-setup.ps1
- scripts/templates/dcos-net/sys.config
* Fix lager log_root and log file
* Add sasl logging module
* Make space-formatting consistent with the rest of the file
* Remove erldns configs and make it consistent with what is given
into the Linux sys.config
* Add telemetry options present in the Linux sys.config. We
still leave forward_metrics disable as it requires dcos_l4lb.
Co-authored-by: Alin Gabriel Serdean aserdean@ovn.org
> Clean-up sys.config template

- scripts/DCOSWindowsAgentSetup.ps1
The changes in this PR is to pre-populate a DC/OS Windows agent with the mesos/windows-health-check Docker image in preparation for the changes in the Meoso core that enabled the usage of windows-health-check image for the Mesos health check
> Pre-populated DCOS Windows agent node with the mesos/windows-health-check docker image

- scripts/DCOSWindowsAgentSetup.ps1
Do the error checking inside the retry block.
The `Start-ExecuteWithRetry` function with latest updates writes timestamps to the stdout. Thus, it is not recommended to be used to capture a return value.
> Fix New-ScriptsDirectory git clone

- scripts/DCOSWindowsAgentSetup.ps1
The previous name `customnat` was too generic.
This fixes issue https://github.com/dcos/dcos-windows/issues/79.
**WARNING**: After this pull request gets merged, all the Marathon JSON files using `customnat` must be updated to use `dcosnat`.
> Rename DC/OS Nat network to 'dcosnat'

- scripts/mesos-agent-setup.ps1
This isolator is used in tandem with windows/cpu for the Mesos
containerizer to correcly enforce memory (and CPU) limits for
non-Docker tasks via job objects.
> Add windows/mem isolator

- scripts/dcos-net-agent-setup.ps1
Until now we were setting the dcos-net DNS server on all interfaces.
We should leave the host interface with its former DNS address.
CC: @ionutbalutoiu
> Set DNS server only on dcos-net interface

- scripts/mesos-agent-setup.ps1
- scripts/variables.ps1
Windows docker images have a great footprint and will take some time until
they are pulled to the local image registry.
Mesos agent has a default 1 min timeout for the registration, unfortunately
this is not enough for the size of the images.
Bump the timeout so the tasks won't be removed if they are in pulling state.
> Add executor registration timeout to the mesos agent on Windows

- scripts/dcos-net-agent-setup.ps1
Unfortunately the host DNS resolvers get passed to the docker containers.
This patch goes back to setting the dcos-net resolvers on every interface.
> Revert upstream DNS resolver on host interface

- scripts/DCOSWindowsAgentSetup.ps1
The change in this PR is to address the DC/OS Windows agent deployment failure by attempting retries when it failed for workaround this file-in-use racing condition:
Error in setting up DCOS Windows Agent: The process cannot access the file 'C:\Program Files\Docker\dockerd.exe' because it is being used by another process.
https://github.com/dcos/dcos-windows/issues/101
> Added retries to the docker binaries copy call

- DCOSWindowsAgentSetup.ps1
* Add `-s` parameter to `curl.exe` to reduce the log messages from the Jenkins console
* Remove `Mesure-Command` wrapper over the PowerShell functions' calls
> Add `-s` (silent) parameter to curl and Remove `Measure-Command` wrapper

- scripts/mesos-agent-setup.ps1
- scripts/variables.ps1
This change depends on:
1. A dcos-engine patch that changes the preprovision scripts to run before the DCOS packages are installed. Dmitry is working on this I think!
2. This pull request and its comments: https://github.com/Microsoft/mesos-jenkins/pull/197
> Changed expected location of mesos environment file.

- systemctl-win/exec/service_exec.cpp
- systemctl-win/exec/service_exec.h
- systemctl-win/src/service_control.cpp
Currently stopping a service either via systemctl or via sc.exe or other service manager tools fails to stop the ExecStart action process tree.  This repairs that.
> service stop

- systemctl-win/exec/ServiceBase.cpp
MSVC complains:
systemctl-win\exec\servicebase.cpp(77): warning C4715: 'CServiceBase::Run': not all control paths return a value
In the case it is in debug mode (the control path that doesn't return a value)
return true.
> systemctl-win: Fix compiler warning in ServiceBase.cpp

- scripts/variables.ps1
Issue: The request to "system/health/v1/nodes/<node ip>/units"  is returning a list of services with the name field empty
This commit fixes the issue by adding the DisplayName of the service to the Description with the following pattern: "DisplayName: Description"
Renamed Service Descriptions to match their Linux counterpart
> Add PrettyName field to Units Response

- Jenkinsfile
The URL that we use is no longer valid. 
We remove the `DCOS_BOOTSTRAP_URL` environment variable and rely on the default value set [here](https://github.com/Microsoft/mesos-jenkins/blob/master/DCOS/dcos-engine-deploy.sh#L32-L34).
> Remove DCOS_BOOTSTRAP_URL environment variable

- scripts/agent-setup.ps1
- scripts/variables.ps1
The second parameter to the `WaitForStatus` method  is a timespan object representing the timeout for waiting the service to be started / stopped.
Passing the string `00:03:00` was not instantiating the desired object representing a timeout of 3 minutes. This pull request fixes this by explicitly creating the timespan object via the `New-TimeSpan` PowerShell cmdlet.
> Fix WaitForStatus method usage

- Jenkinsfile
It is a better approach to give this list from Jenkins instead of having it static in the `Jenkinsfile`.
> Remove MASTER_WHITELISTED_IPS

- scripts/Templates/dcos-net/vm.args
- scripts/dcos-net-agent-setup.ps1
After Erlang got bumped (https://github.com/Microsoft/mesos-jenkins/pull/240) for the Windows build servers, a new version of erts directory is present in the `dcos-net` release package.
> Fix erts directory path used & update vm.args template

- systemctl-win/exec/service_exec.cpp
The function `EvaluateConditions` verify if the service should start.
We returned an error if the conditions were not met, this patch fixes that.
> Conditions specified in service units are not fatal
