scripts/DCOSWindowsAgentSetup.ps1
=> unblock dcos-metrics testing

build_local.ps1, prep_local.ps1, setps1key.ps1
=> Add scripts for performing build actions. Equiv to dcos/dcos

scripts/mesos-agent-setup.ps1
Added external_log_file to mesos agent parameters.
=> Added external_log_file to parameters

scripts/DCOSWindowsAgentSetup.ps1, scripts/Modules/Utils/Utils.psm1, scripts/epmd-agent-setup.ps1, scripts/erlang-setup.ps1, scripts/mesos-agent-setup.ps1, scripts/spartan-agent-setup.ps1
This pull request adds the following updates:
- Create a common `DC/OS` environment file
- Add retries to the `Invoke-WebRequest` calls
- Remove `--log_dir` Mesos parameter
=> Common DC/OS env file, add retries when downloading files and remove Mesos agent '--log_dir' parameter

scripts/mesos-agent-setup.ps1
=> Unified agent log file name to mesos-agent.log, same as the Linux agent.

scripts/adminrouter-agent-setup.ps1
Changes included:
1. Fixed the MSI launch command parameters error, which was causing the MSI package run to fail
2. Added Outbound rules for updating url fields in the response packets
=> Fixed adminrouter package installation issue from the code earlier code changes

scripts/Modules/Utils/Utils.psm1
Until now we only restarted the services upon their failures.
This patch introduces also log rotation for the subsequent failures (more than two failures)
if the service has a log file specified.
I.E.:
if the service has a log file specified
```(start)```->restart_service->restart_service->log rotate/restart_service>log rotate/restart_service
if the service does not have a log file specified
```(start)```->restart_service->restart_service->restart_service>restart_service
=> Add log rotation to service failure

scripts/DCOSWindowsAgentSetup.ps1
The changes in this PR is to address the Docker Stop/Start overlap issue described in the following issue.
https://github.com/dcos/dcos-windows/issues/49
Thanks to Li And Akash's investigation, this PR is to:
1.  collapse the existing two dcoker restarts into one and
2.  make sure docker service transition into  move the desired state
3.  move the customnat creation away from the docker start to avoid any potential async issue from 
docker service start
=> Removed a unnecessary Docker restart and made sure the docker is in desired state before next opertation

scripts/templates/adminrouter/apache_template.conf
The changes in this PR is to trim down the list of loaded Apache modules to the minimum set.
Those removed modules' matching sections were also cleaned.
=> Removed ununsed Apache modules

scripts/DCOSWindowsAgentSetup.ps1, scripts/templates/mesos-http-health/dockerfile.template
This PR is to address the following active issue on RS4:
https://github.com/dcos/dcos-windows/issues/61
=> Generated and preloaded Windows agent with mesos-http-health check Docker image

scripts/DCOSWindowsAgentSetup.ps1
* Fix space-formatting
* Bump Docker version to `18.03.1-ce`
=> Bump Docker version

scripts/metrics-agent-setup.ps1
The change in this PR is to address the following metrics service failure
https://github.com/dcos/dcos-windows/issues/71
=> Added config file to the Metrics service

scripts/DCOSWindowsAgentSetup.ps1
Added logs with timestamp
Using CDN to download Git.exe
=> added logs, use CDN for Git.exe

scripts/dcos-net-agent-setup.ps1
Commit: https://github.com/dcos/dcos-windows/commit/56ef73871e9724a8bf65ef3f45e1dffb49928853
did not take into account the docker interface on the host.
This will cause transient issues when using it's IPv6 because it comes first.
=> Make dcos-net DNS resolvers primary on all interfaces

scripts/DCOSWindowsAgentSetup.ps1
=> Rename `Remove-item` with `Remove-Item`

scripts/DCOSWindowsAgentSetup.ps1
Fixes: https://github.com/dcos/dcos-windows/issues/60.
CC: @ionutbalutoiu
=> Make MSI removals non fatal

scripts/DCOSWindowsAgentSetup.ps1
Get the DCOS directly from the dcos-engine instead of querying the master on the fly, which delaying the completing the Windows agent setup.
This change adds a new parameter to DCOSWindowsAgentSetup.ps1, which requires matching dcos-engine to get the fully benefits of this performance improvement.
For deployments launched by older without matching dcos-engine change, it will fall back to the old logics but no performance improvement
=> Removed the WindowsAgentSetup's dependence on the master's setup operation for speeding up the Windows agent setup

scripts/templates/adminrouter/apache_template.conf
This PR is to pick up the latest config settings from https://github.com/dcos/dcos/pull/2847, which has been merged into the dcos master branch
=> Updated apache_template.conf to sync with the latest adminrouter config in the master

handles/handles/handles.c, scripts/DCOSWindowsAgentSetup.ps1, scripts/DCOSWindowsMasterSetup.ps1, scripts/adminrouter-agent-setup.ps1, scripts/dcos-net-agent-setup.ps1, scripts/detect_ip.ps1, scripts/diagnostics-agent-setup.ps1, scripts/epmd-agent-setup.ps1, scripts/erlang-setup.ps1, scripts/mesos-agent-setup.ps1, scripts/metrics-agent-setup.ps1, scripts/spartan-agent-setup.ps1, service-wrapper/scripts/Build.ps1
Updated the PR.
CC: @soccerGB @ionutbalutoiu
=> Add license header to files

systemctl-win/README.md
=> Add readme

systemctl-win/SystemCtl-Win.vcxproj
=> SystemCtl-Win: Remove non-existent file from project

scripts/diagnostics-agent-setup.ps1
The path to `--endpoint-config` was wrong and this PR fixes it.
In addition to this, we have a config file with all the agent options. This is used instead of passing all the config options as parameters to the wrapper binary.
=> Fix diagnostics-agent config

systemctl-win/README.md, systemctl-win/docs/Systemd-win-diffs.md
Added diffs doc to track what works, what doesn't and what shouldn't.
=> Revised docs

systemctl-win/exec/service_exec.cpp, systemctl-win/exec/service_exec.h, systemctl-win/src/log.cpp
fixes #135 plus fixes spew issue
=> Fixes issue 135, plus fixes spew issue in systemctl

systemctl-win/exec/ServiceBase.cpp, systemctl-win/exec/service_exec.cpp
Reduced cpu use from 15% to 4%. I beleive that is pretty much the background.
=> implemented restart and cat. reduce cpu to acceptable

service-wrapper/.gitignore, service-wrapper/Program.cpp, systemctl-win/exec/ServiceBase.cpp, systemctl-win/exec/ServiceBase.h, systemctl-win/exec/journalstream.cpp, systemctl-win/exec/service_exec.cpp, systemctl-win/exec/service_exec.h, systemctl-win/exec/systemd-exec.cpp, systemctl-win/src/main.cpp, systemctl-win/src/service_control.cpp, systemctl-win/src/service_unit.cpp, systemctl-win/src/service_unit.h, systemctl-win/src/timer_unit.cpp
This PR contains bug fixes and different enhancements for the Windows systemd/systemctl equivalent.
=> Bug fixes and enhancements for systemd wrapper
